
services:
  user_service:
    build: ./UserService
    ports:
      - "7000:7000"
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network

  discussion_service:
    build: ./DiscussionService
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - user_service
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - discussion_service
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spyne
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
